add-docker
Andreation/java-shareit pull request #6
Opened 2023-07-07 15:46 UTC by Andreation

2023-07-07 20:57 UTC, db-exp requested changes

2023-07-07 20:57 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    public BookingClient(@Value("${shareit-server.url}") String serverUrl, RestTemplateBuilder builder) {
подскажи, пожалуйста, откуда тут RestTemplateBuilder появляется?

2023-07-08 13:11 UTC, Andreation commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    public BookingClient(@Value("${shareit-server.url}") String serverUrl, RestTemplateBuilder builder) {
Здесь появляется bean-компонент RestTemplateBuilder по умолчанию, предоставленный Spring Boot

2023-07-08 20:17 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +    public BookingClient(@Value("${shareit-server.url}") String serverUrl, RestTemplateBuilder builder) {
Лучше в таких случая явно создавать свой bean, тогда его можно будет настраивать

2023-07-08 20:17 UTC, db-exp approved these changes

2023-07-27 10:30 UTC, merged